---
title: "Tentative d'opération géométrique"
author: "M. Blondeau"
date: "21/02/2022"
output:
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
knitr::opts_chunk$set(eval = TRUE)
knitr::opts_chunk$set(warning = FALSE)
```

---
library(sf)  
# On charge la librairie sf.

zone <- st_read("data/vote.gpkg", "zone")
str(zone)  
# On regarde la structure du documents. Le premier bureau est considéré comme character et non pas comme integer.  
# Je n'ai pas pu trouver comment faire fusionner les bureaux de vote.

plot(zone$geom, col = terrain.colors (31),
  border = NA,
  main = "31 bureaux de vote de Bondy")  
# On fait ainsi apparaître la première carte. "Main" nous permet de rajouter un titre, tandis que "border = NA" nous permet de supprimer les lignes noires qui délimitait les différentes parties de la carte. 

library(mapsf)  
# On charge la librarie de mapsf, alors qu'on utilisait avant celle de sf (les deux ont précédemment été installées via les commandes 'install.packages("sf")' et install.packages("mapsf")')

mf_map(zone, type = "choro", border = NA, var = "aire")  
# On utilise la commande "mf_map" pour définir les caractéristiques de la carte.  