---
title: "Segment"
author: "B. Maranget"
date: "08/12/2020"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = TRUE)
knitr::opts_chunk$set(warning = FALSE)
```

# Cadre

## Objet

Vérification du fichier résultat segment

## Librairies et répertoire

```{r}
library(sf)
library(cartography)
library(rgdal)
```

# Données

```{r}
# communes sans la corse
commune <- st_read("../dataE/00_ADMIN/ign.gpkg", "commune", quiet = TRUE,stringsAsFactors = F)
# 34868 communes
dpt <- st_read("../dataE/00_ADMIN/ign.gpkg", "dpt", quiet = TRUE, stringsAsFactors = F)
# liste commune canton
com2020 <- read.csv("../dataE/00_ADMIN/communes2020.csv")
can2020 <- read.csv("../dataE/00_ADMIN/canton2020.csv")
# 2 fichiers de segments
segmentV11 <-  st_read("../dataS/segment.gpkg", "v11", stringsAsFactors = F)
segment <- st_read("../dataE/01_CULTURES/segments_syst_L93.shp",  stringsAsFactors = F)
```

## Résultat

Pb de doublons (à résoudre sur le script d'origine)

```{r}
data <- st_read("../dataS/segment.gpkg", "data", quiet = TRUE, stringsAsFactors = TRUE)
# filtre sur les pct100
data100 <- data [data$pct == 100,]
#33150
# recherche des doublons
dataUnique100 <- unique(data100$INSEE_COM)
#34868
tab <- table(data100$INSEE_COM)
id <- names(tab) [tab > 1]
# 1620 doublons
# suppression
data100 <- data100 [order(data100$INSEE_COM),]
dataOK <- data100 [!(duplicated (data100 [, c(1:5), drop = TRUE])),]
# 34 904
setdiff(dataOK$INSEE_COM, commune$INSEE_COM)
# recherche doublon géometrique
# méthode jointure spatiale pour éviter de passer par data100
dataSandDoublon <- st_intersection(data)

```


