---
title: "Bases R"
author: "B. Maranget"
date: "20/01/2021"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = TRUE)
knitr::opts_chunk$set(warning = FALSE)
```

# Objet

Bases R

source : https://github.com/rstudio/cheatsheets/blob/main/base-r.pdf


# Objets R


## Vecteur et dataframe

### Creation

```{r}
nom <- c("Zachary", "Pierre", "Linda")
notes <- c(16,12,13)
df <- as.data.frame(cbind(nom, notes))
df 
```

2 trucs pour survivre :

- Alt + - pour l'opérateur d'assignation

- tabulation pour la complétion

### Indexation

```{r}
nom [1]
notes [2]
df [1,2]
```

```{r}
df$nom
df$notes
```

### Operation

```{r}
#sum(df$notes)
sum(notes)
```

## Exercice


Créer un dataframe sur 3 villes et leur nombre d'habitants
Trouver la moyenne du nombre d'habitants.




