---
title: "Sorgho"
author: "B. Maranget"
date: "6/1/2020"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = TRUE)
knitr::opts_chunk$set(warning = FALSE)
```

# Objet

Carte de surface et de rendement sorgho

## Librairies et répertoire

```{r}
library(sf)
library(cartography)

```

# Préparer la donnée

## Données

```{r}
dpt <- st_read("../dataE/00_ADMIN/ign.gpkg", "dptCorse", quiet = TRUE, stringsAsFactors = F)
region <- st_read("../dataE/00_ADMIN/ign.gpkg", "region", quiet = TRUE, stringsAsFactors = F)
# chargement donnée
rdt <- read.csv("../dataE/01_CULTURES/sorghoRdt.csv")
surface <- read.csv("../dataE/01_CULTURES/sorghoSurface.csv")
head(rdt)
str(rdt)
rdt <- rdt [,c(2:3)]
names(rdt) <- c("dpt", "rdt")
head(surface)
surface <- surface [, c(1:2)]
names (surface) <- c("dpt", "aire")
str(surface)
surface$aire <- gsub(",", ".", surface$aire)
surface$aire <- as.numeric(surface$aire)
```

## Jointure du fichier

```{r}
str(dpt)
head(dpt)
rdt$INSEE_DEP <- substr(rdt$dpt, 1,2)
surface$INSEE_DEP <- substr(surface$dpt, 1,2)
data <- merge(dpt, surface, all.x = TRUE, by = "INSEE_DEP")
data <- merge(data, rdt, all.x = TRUE, by = "INSEE_DEP")
head(data)
data <- data [, c("NOM_DEP", "INSEE_DEP", "rdt", "aire")]
st_write(data, "../dataS/sorgho.gpkg", "data", quiet = TRUE, delete_layer = TRUE)
```

